import sys

def solve():
    data = list(map(int, sys.stdin.buffer.read().split()))
    t = data[0]
    idx = 1
    ans = []

    def get_basis(arr):
        basis = [0] * 30
        for x in arr:
            y = x
            for i in range(29, -1, -1):
                if ((y >> i) & 1) == 0:
                    continue
                if basis[i]:
                    y ^= basis[i]
                else:
                    basis[i] = y
                    break
        return basis

    def reduce_basis(x, basis):
        y = x
        for i in range(29, -1, -1):
            if (y >> i) & 1 and basis[i]:
                y ^= basis[i]
        return y

    for _ in range(t):
        n = data[idx]
        idx += 1

        a = data[idx:idx+n]
        idx += n

        b = data[idx:idx+n]
        idx += n

        # The multiset of linear dependencies must be preserved.
        # Check if every difference b[i]^a[i] belongs to the span
        # generated by the differences of the original array.

        diff = [a[i] ^ b[i] for i in range(n)]
        basis = get_basis(a)

        ok = True
        for x in diff:
            if reduce_basis(x, basis) != 0:
                ok = False
                break

        ans.append("YES" if ok else "NO")

    print("\n".join(ans))

if __name__ == "__main__":
    solve()